apiVersion: v1
kind: PersistentVolume
metadata:
  name: httpd-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: httpd-web
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pvc
spec:
  storageClassName: ""
  volumeName: httpd-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
